sudo: required

services:
  -docker

before_install:
  - docker build -t kiano/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kiano/react-test yarn test -- --coverage

after_success:
  - docker build -t kiano/multi-client ./client
  - docker build -t kiano/multi-nginx ./nginx
  - docker build -t kiano/multi-server ./server
  - docker build -t kiano/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kiano/multi-client
  - docker push kiano/multi-nginx
  - docker push kiano/multi-server
  - docker push kiano/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-174096802200
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY